name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pip install pylint
        ls
        pylint houdini/
        ...

    - name: Lint with black
      run: |
        pip install black
        black houdini/
        ...

    - name: Lint with isort
      run: |
        pip install isort
        isort houdini/
        ...

    - name: Lint with pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle houdini/
        ...

    - name: Lint with mypy
      run: |
        pip install mypy
        
        mypy houdini/
        ...
